ExemploMVC02/ExemploMVC02/Models/Recrutadora.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ExemploMVC02.Models
{
    public class Recrutadora
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Nome não pode ser vazio")]
        [MinLength(7,ErrorMessage = "Nome deve conter no mínimo 7 caracteres")]
        [MaxLength(100,ErrorMessage = "Nome deve conter no máximo 100 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "CPF não pode ser vazio")]
        [MinLength(11, ErrorMessage = "CPF deve conter somente 11 digitos")]
        public string CPF { get; set; }

        [Required(ErrorMessage = "Tempo de empresa deve ser preenchido")]
        [Range(0, 6, ErrorMessage = "Pessoa deve ter entre 0 à 6 anos de empresa")]
        public byte TempoEmpresa { get; set; }

        [Required(ErrorMessage = "Salário deve ser preenchido")]
        [Range(1200.00, 100000.00, ErrorMessage = "Salário deve estar entre R$ 1.200,00 à R$ 100.000,00")]
        public decimal Salario { get; set; }
    }
}

ExemploMVC02/ExemploMVC02/Controllers/RecrutadoraController.cs
using ExemploMVC02.Models;
using ExemploMVC02.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExemploMVC02.Controllers
{
    public class RecrutadoraController : Controller
    {
        // GET: Recrutadora
        [HttpGet]
        public ActionResult Index()
        {
            List<Recrutadora> recrutadoras = new RecrutadoraRepository().ObterTodos();
            ViewBag.Recrutadoras = recrutadoras;
            ViewBag.TituloPagina = "Recrutadoras";
            return View();
        }

        [HttpGet]
        public ActionResult Cadastro()
        {
            ViewBag.TituloPagina = "Recrutadoras Cadastro";
            ViewBag.Recrutadora = new Recrutadora();
            return View();
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Recrutadora recrutadora = new RecrutadoraRepository().ObterPeloId(id);
            ViewBag.Recrutadora = recrutadora;
            ViewBag.TituloPagina = "Recrutadoras Editar";
            return View();
        }

        [HttpGet]
        public ActionResult Excluir(int id)
        {
            bool apagado = new RecrutadoraRepository().Excluir(id);
            return null;
        }

        [HttpPost]
        public ActionResult Store(Recrutadora recrutadora)
        {
            if (ModelState.IsValid)
            {
                recrutadora.CPF = recrutadora.CPF.Replace(".", "").Replace("-", "");
                int identificador = new RecrutadoraRepository().Cadastrar(recrutadora);
                return RedirectToAction("Editar", new { id = identificador });
            }

            ViewBag.Recrutadora = recrutadora;
            return View("Cadastro");

        }

        [HttpPost]
        public ActionResult Update(Recrutadora recrutadora)
        {
            bool alterado = new RecrutadoraRepository().Alterar(recrutadora);
            return null;
        }
    }
}

ExemploMVC02/ExemploMVC02/Views/Recrutadora/Cadastro.cshtml
@{
    Layout = "~/Views/Shared/Master.cshtml";
}



<div class="row mt-3">
    <div class="col-md-12">
        <h5 class="text-primary text-center">Cadastro de Recrutadora</h5>
    </div>
</div>



<div class="row">
    <div class="col-md-6 offset-md-3">
        <form action="/Recrutadora/Store" method="post" onsubmit="validarFormulario();">
            <div class="form-group" id="div-campo-nome">
                <label for="campo-nome">
                    Nome Completo<span class="text-danger font-weight-bold">*</span>
                </label>
                <input type="text" name="Recrutadora.Nome" id="campo-nome" class="form-control" required="required" onfocusout="validarCampoNome()" value="@ViewBag.Recrutadora.Nome" />
                @Html.ValidationMessage("Recrutadora.Nome", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="campo-cpf">
                    CPF <span class="text-danger font-weight-bold">*</span>
                </label>
                <input type="text" name="Recrutadora.Cpf" id="campo-cpf" class="form-control" required="required" value="@ViewBag.Recrutadora.CPF" />
                @Html.ValidationMessage("Recrutadora.CPF", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="campo-salario">
                    Salário <span class="text-danger font-weight-bold">*</span>
                </label>
                <input type="text" name="Recrutadora.Salario" id="campo-salario" class="form-control" required="required" value="@ViewBag.Recrutadora.Salario" />
                @Html.ValidationMessage("Recrutadora.Salario", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="campo-tempo-empresa">
                    Tempo empresa
                    <span class="text-danger font-weight-bold">*</span>
                </label>
                <select id="campo-tempo-empresa" name="Recrutadora.TempoEmpresa" class="form-control" required="required">
                    <option value="0">0 ano</option>
                    <option value="1">1 ano</option>
                    <option value="2">2 ano</option>
                    <option value="3">3 ano</option>
                    <option value="4">4 ano</option>
                    <option value="5">5 ano</option>
                    <option value="6">6 ano</option>
                </select>
                @Html.ValidationMessage("Recrutadora.TempoEmprese", new { @class = "text-danger" })
            </div>

            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-success float-right">
                        <i class="fa fa-save"></i> Cadastrar
                    </button>
                </div>
            </div>
        </form>
    </div>

</div>

ExemploMVC02/ExemploMVC02/Views/Recrutadora/Editar.cshtml
@{
    Layout = "~/Views/Shared/Master.cshtml";
}

<div class="row mt-3">
    <div class="col-md-12">
        <h5 class="text-primary text-center">Editar de Recrutadora</h5>
    </div>
</div>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <form action="/Recrutadora/Update" method="post">
            <input type="hidden" name="Recrutadora.Id" value="@ViewBag.Recrutadora.Id" />
            <div class="form-group">
                <label for="campo-nome">Nome <span class="text-danger font-weight-bold">*</span>
                </label>
                <input type="text" name="Recrutadora.Nome" id="campo-nome" value="@ViewBag.Recrutadora.Nome" class="form-control" required="required" />
                @Html.ValidationMessage("Recrutadora.Nome", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="campo-cpf">CPF <span class="text-danger font-weight-bold">*</span>
                </label>
                <input type="text" name="Recrutadora.Cpf" id="campo-cpf" value="@ViewBag.Recrutadora.CPF" class="form-control" required="required" />
                @Html.ValidationMessage("Recrutadora.CPF", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="campo-salario">Salário <span class="text-danger font-weight-bold">*</span>
                </label>
                <input type="text" name="Recrutadora.Salario" id="campo-salario" value="@ViewBag.Recrutadora.Salario" class="form-control" required="required" />
                @Html.ValidationMessage("Recrutadora.Salario", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label for="campo-tempo-empresa">Tempo empresa <span class="text-danger font-weight-bold">*</span>
                </label>
                <select id="campo-tempo-empresa" name="Recrutadora.TempoEmpresa" class="form-control" required="required">
                    @for (int i = 0; i < 7; i++)
                    {
                        if (i == @ViewBag.Recrutadora.TempoEmpresa)
                        {
                            <option value="@i" selected="selected">@i anos</option>
                        }
                        else
                        {
                            <option value="@i">@i anos</option>
                        }
                    }
                </select>
                @Html.ValidationMessage("Recrutadora.TempoEmpresa", new { @class = "text-danger" })
            </div>

            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-warning float-right">
                        <i class="fa fa-pencil-alt"></i> Salvar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

ExemploMVC02/ExemploMVC02/Views/Recrutadora/Index.cshtml
@{
    Layout = "~/Views/Shared/Master.cshtml";
}


@Html.ActionLink("Nova Recrutadora", "Cadastro", "Recrutadora", new { @class = "btn btn-primary float-right mr-2 mb-2 mt-2" })
<div class="mr-3 ml-3">
    <table class="table table-striped table-hover">
        <thead>
            <tr class="bg-secondary text-white">
                <th>Código</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Ação</th>
            </tr>
        </thead>

        <tbody>
            @foreach (ExemploMVC02.Models.Recrutadora recrutadora in @ViewBag.Recrutadoras)
            {
                <tr>
                    <td>@recrutadora.Id</td>
                    <td>@recrutadora.Nome</td>
                    <td>@recrutadora.CPF</td>
                    <td>
                        <a href="/Recrutadora/Editar?id=@recrutadora.Id" class="btn btn-outline-success">
                            <i class="fa fa-edit"></i> Editar
                        </a>
                        <a href="/Recrutadora/Excluir?id=@recrutadora.Id" class="btn btn-outline-danger">
                            <i class="fa fa-trash"></i> Excluir
                        </a>
                    </td>
                </tr>
            }
        </tbody>

        <tfoot>
            <tr class="bg-secondary text-white">
                <th>Código</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Ação</th>
            </tr>
        </tfoot>
    </table>
</div>

ExemploMVC02/ExemploMVC02/Views/Shared/Master.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.TituloPagina</title>
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/all.css">
    <script src="~/Content/bootstrap/js/bootstrap.js"></script>
    <script src="~/Scripts/Recrutadora/cadastro.js"></script>
</head>
<body>
    <div class="container-fluid"> 
        @RenderBody()
    </div>
</body>
</html>

ExemploMVC02/ExemploMVC02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>